#!/bin/bash

DEBUG="$1"

if [ "$DEBUG" == "" ] ; then
    DEBUG="false"
fi

echo "building cleaner"
echo "> coffee -c -o dst src/cleaner/cleaner.coffee"
coffee -c -o dst src/cleaner/cleaner.coffee

echo "building parser"
echo "> jison -o dst/parser.js src/parser/ascent.jison src/lexer/ascent.jisonlex"
jison --debug "$DEBUG" -o dst/parser.js src/parser/ascent.jison src/lexer/ascent.jisonlex

echo "patching cli"
echo "> patch dst/parser.js cli.patch"
patch dst/parser.js cli.patch

echo "building package"
echo "> coffee -c -o dst src/nodes.coffee"
coffee -c -o dst src/nodes.coffee
echo "> coffee -c -o dst src/ascent.coffee"
coffee -c -o dst src/ascent.coffee

echo "success!"
