#!/bin/bash

DEBUG="$1"

if [ "$DEBUG" == "" ] ; then
    DEBUG="false"
fi

echo "building parser"
echo "> jison -o dst/ascent.js src/parser/ascent.jison src/lexer/ascent.jisonlex"
jison --debug "$DEBUG" -o dst/ascent.js src/parser/ascent.jison src/lexer/ascent.jisonlex
echo "patching cli"
echo "> patch dst/ascent.js cli.patch"
patch dst/ascent.js cli.patch
echo "success!"
