#!/bin/bash

coffee test/cleaner/comments.coffee

coffee test/parser/booleans.coffee
coffee test/parser/classes.coffee
coffee test/parser/inner_classes.coffee
coffee test/parser/initializer.coffee
coffee test/parser/methods.coffee
coffee test/parser/names.coffee
coffee test/parser/numbers.coffee
coffee test/parser/properties.coffee
coffee test/parser/strings.coffee
coffee test/parser/statements.coffee
coffee test/parser/expressions.coffee
coffee test/parser/collections.coffee
coffee test/parser/runas.coffee
coffee test/parser/typecast.coffee

coffee test/nodes/classes.coffee

./parseAll test/classes/*
