#!/bin/bash

coffee test/parser/classes.coffee
coffee test/parser/comments.coffee
coffee test/parser/inner_classes.coffee
coffee test/parser/initializer.coffee
coffee test/parser/methods.coffee
coffee test/parser/names.coffee
coffee test/parser/numbers.coffee
coffee test/parser/properties.coffee
coffee test/parser/strings.coffee
