public class Statements
{
    public void foobar()
    {
        for ( Integer j = 4; true; )
        {
            String baz = 'bam';
        }

        try
        {
            if ( false )
            {
                throw ex;
            }
        }
        catch ( Exception ex )
        {
            Integer i = 5;
        }
        finally
        {
            String foo = 'bar';
        }
    }
}
